[package]
name = "yew-property-info"
version = "0.1.0"
authors = ["Bytebuddha <pmg41494@protonmail.com>"]
edition = "2018"

[workspace]
members = [
    "derive"
]

[dependencies]
yew-property-info-derive = { path = "derive" }

[dev-dependencies]
yew = "*"
